# Generated by Django 5.0.6 on 2024-08-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='markers/')),
            ],
        ),
    ]
