# Generated by Django 5.0.6 on 2024-08-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_marker_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
