# Generated by Django 5.0.6 on 2024-08-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_marker_end_date_marker_is_permanent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='icon',
        ),
        migrations.AlterField(
            model_name='marker',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
